#include <iostream>
#include <stdexcept>
#include <string>

using namespace std;

double divide(double a, double b) {
    if (b == 0) {
        throw runtime_error("Ошибка: Деление на ноль!");
    }
    return a / b;
}

int main() {
    double num1, num2;
    string input;

    cout << "Введите первое число: ";
    cin >> input;
    try {
        num1 = stod(input); 
    } catch (const invalid_argument&) {
        cout << "Ошибка: Некорректные данные для первого числа!" << endl;
        return 1;
    }

    cout << "Введите второе число: ";
    cin >> input;
    try {
        num2 = stod(input);
    } catch (const invalid_argument&) {
        cout << "Ошибка: Некорректные данные для второго числа!" << endl;
        return 1;
    }

    try {
        double result = divide(num1, num2);
        cout << "Результат деления: " << result << endl;
    } catch (const runtime_error& e) {
        cout << e.what() << endl;
    } catch (...) {
        cout << "Произошла неожиданная ошибка!" << endl;
    }

}
